/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Nova paleta de cores - Alimentação Sem Medo
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'accent-primary': 'var(--color-accent-primary)',
        'accent-secondary': 'var(--color-accent-secondary)',
        'bg-light': 'var(--color-bg-light)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        // Variáveis de compatibilidade
        'dark-bg': 'var(--color-bg-primary)',
        'dark-secondary': 'var(--color-bg-secondary)',
        'dark-tertiary': '#1A4A45',
        'dark-card': 'var(--color-bg-secondary)',
        'dark-border': 'var(--color-accent-secondary)',
        'olive': 'var(--color-accent-primary)',
        'olive-dark': '#5A7A2F',
        'olive-light': '#7FA04A',
        'olive-accent': 'var(--color-accent-primary)',
        'beige': 'var(--color-bg-light)',
        'beige-light': '#F9FAF7',
        'beige-warm': '#F7F9F4',
        'beige-soft': 'var(--color-bg-light)',
        'petrol': 'var(--color-bg-secondary)',
        'petrol-dark': 'var(--color-bg-primary)',
        'petrol-light': '#1A4A45',
        'petrol-accent': 'var(--color-accent-secondary)',
        'text-soft': '#9FB0A5',
        'text-muted': '#7A8E82',
        'neon-blue': 'var(--color-accent-secondary)',
        'neon-cyan': 'var(--color-accent-secondary)',
        'neon-purple': 'var(--color-accent-primary)',
        'neon-pink': 'var(--color-accent-primary)',
        'neon-green': 'var(--color-accent-primary)',
        'lilac': 'var(--color-accent-primary)',
      },
      fontFamily: {
        sans: ['var(--font-montserrat-light)', 'system-ui', 'sans-serif'],
        display: ['var(--font-montserrat-light)', 'system-ui', 'sans-serif'],
        body: ['var(--font-montserrat-light)', 'system-ui', 'sans-serif'],
        light: ['var(--font-montserrat-light)', 'system-ui', 'sans-serif'],
        bold: ['var(--font-montserrat-bold)', 'system-ui', 'sans-serif'],
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      fontSize: {
        'base': '18px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '28px',
        '3xl': '32px',
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.3)',
        'medium': '0 4px 16px rgba(0, 0, 0, 0.4)',
        'large': '0 8px 24px rgba(0, 0, 0, 0.5)',
        'card': '0 20px 40px rgba(0, 0, 0, 0.35), inset 0 1px 0 rgba(255, 255, 255, 0.03)',
        'card-glow': '0 0 0 1px rgba(110, 143, 61, 0.4), 0 0 25px rgba(110, 143, 61, 0.25), 0 20px 40px rgba(0, 0, 0, 0.35), inset 0 1px 0 rgba(255, 255, 255, 0.03)',
        'btn-hover': '0 8px 25px rgba(110, 143, 61, 0.4)',
        'glow-olive': '0 0 20px rgba(110, 143, 61, 0.3), 0 0 40px rgba(110, 143, 61, 0.15)',
        'glow-moss': '0 0 20px rgba(79, 107, 88, 0.3), 0 0 40px rgba(79, 107, 88, 0.15)',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 3s ease-in-out infinite alternate',
      },
      keyframes: {
        glow: {
          '0%': { opacity: '0.6' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
